name: GitHub Screenshot Action
description:
  An action to take screenshot(s) of websites from GitHub Actions pipelines.
author: Guilherme Branco Stracini

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: camera
  color: green

# Define your inputs here.
inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
